# Generated by Django 5.2.12 on 2026-05-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0005_alter_identifier_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifier',
            options={},
        ),
    ]
