# Generated by Django 5.2.12 on 2026-05-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0010_alter_adjudicatoradjudicatorconflict_unique_together_and_more'),
        ('adjfeedback', '0020_silent_round_feedback'),
        ('draw', '0011_debate_scheduled_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='silentroundfeedback',
            name='unique_silent_feedback_per_adj_per_debate',
        ),
        migrations.AlterUniqueTogether(
            name='silentroundfeedback',
            unique_together={('debate', 'submitted_by')},
        ),
    ]
